#!/usr/bin/env bash
# This script displays information about subdomains of a domain.

domain=$1
subdomain=$2

subdomains=("www" "lb-01" "web-01" "web-02")

# Function to retrieve DNS information for a subdomain
get_dns_info() {
    local sub=$1
    local dns_info=$(dig "${sub}.${domain}" | awk '/^'${sub}'\.'${domain}'\./ {print $5}')
    echo "The subdomain ${sub} is a $(echo ${dns_info} | awk '{print $2}') record and points to $(echo ${dns_info} | awk '{print $4}')"
}

# Check if subdomain argument is provided
if [ -z "${subdomain}" ]; then
    # Iterate over predefined subdomains and display DNS record information
    for sub in "${subdomains[@]}"; do
        get_dns_info "${sub}"
    done
else
    # Display DNS record information for the specified subdomain
    get_dns_info "${subdomain}"
fi
