#!/usr/bin/env bash
# Bash script to install and configure Nginx web server

# Install Nginx
apt-get update
apt-get -y install nginx

# Start Nginx service
service nginx start

# Configure Nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx
killall -9 nginx
nginx -g "daemon off;" &

# Create index.html with "Hello World!" message
echo "Hello World!" > /var/www/html/index.html

exit 0
