#!/usr/bin/env bash
# This script configures Nginx with a custom HTTP response header

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx custom header
sudo sed -i '/server_name _;/a \\n\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Restart Nginx service
sudo service nginx restart
