#!/usr/bin/env bash
# This script installs and configures HAProxy as a load balancer

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 753-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 753-web-02 52.86.149.92:80 check\n\tserver 753-web-01 100.25.166.233:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
