#!/usr/bin/env bash
# Install the load balancer

#!/usr/bin/env bash

# Update system packages
sudo apt-get update

# Install HAProxy
sudo apt-get -y install haproxy

# Configure HAProxy
sudo sed -i 's/^\(.*\)#\?frontend.*$/\1frontend lb_frontend\n\tbind \*:80\n\tmode http\n\tdefault_backend lb_backend/' /etc/haproxy/haproxy.cfg
sudo sed -i 's/i^\(.*\)#\?backend.*$/\1backend lb_backend\n\tmode http\n\tbalance roundrobin\n\tserver web-01 753-web-01:80 check\n\tserver web-02 753-web-02:80 check/' /etc/haproxy/haproxy.cfg

# Restart HAProxy service
sudo service haproxy restart

