#!/usr/bin/env bash
# This script configures an Ubuntu server to resolve localhost to 127.0.0.2 and facebook.com to 8.8.8.8.

cp /etc/hosts ~/hosts.new
sed -i 's/localhost$/&\n127.0.0.2/' ~/hosts.new
sed -i 's/facebook.com/8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts

