#!/usr/bin/env bash
# This script configures the container to run Nginx as the nginx user.

sed -i 's/user nginx;/user nginx nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
service nginx restart
